#!/bin/bash
set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/run.bash
. "$DIR/../lib/run.bash"
# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"
# shellcheck source=lib/metadata.bash
. "$DIR/../lib/metadata.bash"

# run docker clean up at start if pre-cleanup is enabled
if [[ "$(plugin_read_config PRE_CLEANUP "false")" == "true" ]]; then
  echo "~~~ :docker: Pre-cleaning docker-compose" >&2
  FOUND_CONTAINERS=$(docker ps -aq)
  if [[ -z "$FOUND_CONTAINERS" ]]; then
    echo "No Docker containers found to delete"
  else
    echo "Removing Docker containers:"
    docker rm -f `echo $FOUND_CONTAINERS`
  fi
  docker volume prune -f
fi

# skip checkout if skip-checkout is set
if [[ "$(plugin_read_config SKIP_CHECKOUT "false")" == "true" ]] ; then
  export BUILDKITE_REPO=""
  export BUILDKITE_PLUGIN_DOCKER_COMPOSE_REQUIRE_PREBUILD="true"
fi
