#!/bin/bash
set -ueo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/run.bash
. "$DIR/../lib/run.bash"
# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"
# shellcheck source=lib/metadata.bash
. "$DIR/../lib/metadata.bash"

# run docker clean up at start if pre-cleanup is enabled
if [[ "$(plugin_read_config PRE_CLEANUP "false")" == "true" ]]; then
  echo "~~~ :docker: Pre-cleaning docker-compose" >&2
  FOUND_PROJECTS=$(docker compose ls -q)
  if [[ -z "$FOUND_PROJECTS" ]]; then
    echo "No Docker Compose projects found to delete"
  else
    echo "Removing Docker Compose projects:"
    for str in ${FOUND_PROJECTS//;/ } ; do
       docker-compose -p "$str" down
    done
  fi
fi

# skip checkout if skip-checkout is set
if [[ "$(plugin_read_config SKIP_CHECKOUT "false")" == "true" ]] ; then
  export BUILDKITE_REPO=""
  export BUILDKITE_PLUGIN_DOCKER_COMPOSE_REQUIRE_PREBUILD="true"
fi
